# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8

  - repo: git://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
    - id: csslint

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: minify-css
      name: Minify CSS
      entry: "python ./minify-css.py"
      language: system
      types: ["file", "text"]
      files: "bs-.*\\.css$"
      pass_filenames: false
